<?php

namespace Tropi\CampsBundle\Entity;

/**
 * CentraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentraleRepository extends \Doctrine\ORM\EntityRepository
{
}
