# TROPICAMPS

# page d'accueil du site
tc_homepage:
    path:     /
    defaults: { _controller: TropiCampsBundle:Utilisateur:index }
# page dediee au refugie(id)
tc_refugie:
    path: /ref/{id}
    defaults: { _controller: TropiCampsBundle:Utilisateur:refugie }
# page dediee au camp(id)
tc_camp:
    path: /camp/{id}
    defaults: { _controller: TropiCampsBundle:Utilisateur:camp }
# page des resultats de la recherche
tc_recherche:
    path: /result
    defaults: { _controller: TropiCampsBundle:Utilisateur:recherche }


# TROPICAMPS ADMIN

# page d'accueil du Staff
tca_homepage:
    path: /admin
    defaults: { _controller: TropiCampsBundle:Staff:index }
tca_ref:
    path: /admin/refugie
    defaults: { _controller: TropiCampsBundle:Staff:ref }
# ajouter un refugie // a supprimer
tca_add_refugie:
    path: /admin/refugie/add
    defaults: { _controller: TropiCampsBundle:Staff:addRef }
# modifier un refugie
tca_mod_refugie:
    path: /admin/refugie/mod/{id}
    defaults: { _controller: TropiCampsBundle:Staff:modRef }
# supprimer un refugie
tca_del_refugie:
    path: /admin/refugie/del/{id}
    defaults: { _controller: TropiCampsBundle:Staff:delRef }
tca_camp:
    path: /admin/camp
    defaults: { _controller: TropiCampsBundle:Staff:camp }
# ajouter un refugie // a supprimer
tca_camp_page:
    path: /admin/camp/{id}
    defaults: { _controller: TropiCampsBundle:Staff:campPage }
tca_stock:
    path: /admin/stock
    defaults: { _controller: TropiCampsBundle:Staff:stock }
tca_stock_page:
    path: /admin/stock/{id}
    defaults: { _controller: TropiCampsBundle:Staff:stockPage }
tca_stock_add:
    path: /admin/stock/{id}/{pid}/add
    defaults: { _controller: TropiCampsBundle:Staff:stockAdd }
tca_stock_sub:
    path: /admin/stock/{id}/{pid}/sub
    defaults: { _controller: TropiCampsBundle:Staff:stockSub }
tca_stock_def:
    path: /admin/stock/{id}/{pid}/def
    defaults: { _controller: TropiCampsBundle:Staff:stockDef }
